# Generated by Django 3.2 on 2021-05-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cuisine_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.cuisine'),
        ),
    ]
